/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ArtStyles1GETWorldsArtStylesSelectableWorldArtStylesInDisplayOrder {
  schema_version: "art_styles/1";
  styles: {
    key: string;
    label: string;
    blurb: string;
  }[];
}
