/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BeatFrame5OneSSEFrameOfPOSTWorldsWBeatsSupersedesBeatFrame4WithNarrationEmotionAndEmbeddedSceneCurrent4Sprites =
  InterpretationFrame | NarrationFrame | SceneFrame | JourneyFrame | ResultFrame | ErrorFrame | TraceFrame;
export type Attempt =
  | {
      type: "ActorMoved";
      stated: string;
      to_target_id: string;
    }
  | {
      type: "Communicated";
      stated: string;
      listener_id: string;
      content: string;
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
      sustain?:
        | {
            kind: "for";
            seconds: number;
          }
        | {
            kind: "until_at";
            entity_id: string;
            place_id: string;
          }
        | {
            kind: "until_attr";
            entity_id: string;
            attr: string;
            value: string;
          };
    }
  | {
      type: "ObjectRelocated";
      stated: string;
      object_id: string;
      dest_kind: "actor" | "location" | "container";
      dest_id: string;
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
      sustain?:
        | {
            kind: "for";
            seconds: number;
          }
        | {
            kind: "until_at";
            entity_id: string;
            place_id: string;
          }
        | {
            kind: "until_attr";
            entity_id: string;
            attr: string;
            value: string;
          };
    }
  | {
      type: "OwnershipAccessChanged";
      stated: string;
      target_id: string;
      grantee_id?: string;
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
      sustain?:
        | {
            kind: "for";
            seconds: number;
          }
        | {
            kind: "until_at";
            entity_id: string;
            place_id: string;
          }
        | {
            kind: "until_attr";
            entity_id: string;
            attr: string;
            value: string;
          };
    }
  | {
      type: "EntityCreated";
      stated: string;
      component_ids?: string[];
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
      sustain?:
        | {
            kind: "for";
            seconds: number;
          }
        | {
            kind: "until_at";
            entity_id: string;
            place_id: string;
          }
        | {
            kind: "until_attr";
            entity_id: string;
            attr: string;
            value: string;
          };
    }
  | {
      type: "EntityDestroyed";
      stated: string;
      target_id: string;
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
      sustain?:
        | {
            kind: "for";
            seconds: number;
          }
        | {
            kind: "until_at";
            entity_id: string;
            place_id: string;
          }
        | {
            kind: "until_attr";
            entity_id: string;
            attr: string;
            value: string;
          };
    }
  | {
      type: "AttributeChanged";
      stated: string;
      target_id: string;
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
      sustain?:
        | {
            kind: "for";
            seconds: number;
          }
        | {
            kind: "until_at";
            entity_id: string;
            place_id: string;
          }
        | {
            kind: "until_attr";
            entity_id: string;
            attr: string;
            value: string;
          };
    }
  | {
      type: "UNRESOLVED";
      stated: string;
      reference: string;
      /**
       * @minItems 2
       */
      candidate_ids: [string, string, ...string[]];
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
    }
  | {
      type: "QUERY";
      stated: string;
      /**
       * @minItems 1
       */
      query_target_ids: [string, ...string[]];
      duration_class?: "instant" | "short" | "medium" | "long" | "extremely_long";
    };

export interface InterpretationFrame {
  schema_version: "beat_frame/5";
  kind: "interpretation";
  chain: Attempt[];
}
export interface NarrationFrame {
  schema_version: "beat_frame/5";
  kind: "narration";
  message: {
    speaker_id: string | null;
    speaker_label: string;
    kind: "narration" | "speech" | "action";
    /**
     * Prose. The whole segment for narration and action; for speech it is the STAGING around the line and may be empty when the line is delivered bare.
     */
    text: string;
    /**
     * The verbatim spoken words, without quotation marks or attribution. Non-empty exactly when kind is speech; null otherwise. Render it as speech; render `text` as prose.
     */
    quote: string | null;
    /**
     * Optional per-line speaker emotion for sprite selection. Null/absent means neutral.
     */
    emotion?: "neutral" | "happy" | "angry" | "sad" | null;
  };
}
export interface SceneFrame {
  schema_version: "beat_frame/5";
  kind: "scene";
  scene: SceneCurrent4WhereYouAreWhoIsPresentWhatMattersNowGETWorldsWSceneCurrent;
}
/**
 * EMBEDDED COPY of the published scene_current/3 payload — the scene frame carries the identical object GET /worlds/{w}/scene/current returns. It is duplicated rather than $ref'd because ci/schema_contract.py loads each schema file independently and has no cross-file resolver. THE COUPLING IS REAL AND HAS BITTEN: bumping scene_current invalidates this branch and therefore forces a beat_frame bump too, which is how /3 happened. Keep them in lockstep, or give the checker a resolver and $ref this instead.
 */
export interface SceneCurrent4WhereYouAreWhoIsPresentWhatMattersNowGETWorldsWSceneCurrent {
  schema_version: "scene_current/4";
  place: {
    id: string;
    label: string;
    description: string | null;
    tone: string | null;
    /**
     * The play-surface BACKDROP for the place the viewer stands in. Not perception-scoped, for the same reason a portrait is not: the room you are standing in is not a secret, and what the viewer KNOWS about it is already carried by label and description. Image reference, or null when there is no picture yet — the ordinary state, and what the frontend's placeholder is for. It swaps in on a later read with no re-request and no subscription. Carries an asset id and a PATH back to the world backend, never a presigned URL: those expire (~15 min), so an embedded one would make this payload rot in any cache or log. Fetch as {apiBase}{path}, optionally ?tier=thumbnail|preview|final (256/768/1024, default preview); the backend mints a fresh short-lived URL per read and redirects.
     */
    image: null | {
      schema_version: "image_ref/1";
      asset_id: string;
      path: string;
    };
  };
  participants: {
    id: string;
    label: string;
    kind: "actor";
    /**
     * Image reference, or null when there is no picture yet — the ordinary state, and what the frontend's placeholder silhouette is for. It swaps in on a later read with no re-request and no subscription. Carries an asset id and a PATH back to the world backend, never a presigned URL: those expire (~15 min), so an embedded one would make this payload rot in any cache or log. Fetch as {apiBase}{path}, optionally ?tier=thumbnail|preview|final (256/768/1024, default preview); the backend mints a fresh short-lived URL per read and redirects.
     */
    image: null | {
      schema_version: "image_ref/1";
      asset_id: string;
      path: string;
    };
    /**
     * Sprite set for the participant. Null until all four emotion variants exist; non-null only when every variant is filled.
     */
    sprites: null | {
      neutral: {
        schema_version: "image_ref/1";
        asset_id: string;
        path: string;
      };
      happy: {
        schema_version: "image_ref/1";
        asset_id: string;
        path: string;
      };
      angry: {
        schema_version: "image_ref/1";
        asset_id: string;
        path: string;
      };
      sad: {
        schema_version: "image_ref/1";
        asset_id: string;
        path: string;
      };
    };
  }[];
  now: {
    tick: number;
    display_label: string | null;
  };
  journey: null | JourneyBlock;
  current: string[];
}
export interface JourneyBlock {
  active: boolean;
  kind: "travel" | "wait" | "watch";
  goal_label: string | null;
  where_label: string | null;
  progress: number;
  legs_done: number;
  legs_total: number;
  interruptible: boolean;
  status: "active" | "arrived" | "ended";
}
export interface JourneyFrame {
  schema_version: "beat_frame/5";
  kind: "journey";
  journey: null | JourneyBlock;
}
export interface ResultFrame {
  schema_version: "beat_frame/5";
  kind: "result";
  result: {
    committed: string[];
    halt_reason: string;
    ticks_advanced: number;
    unresolved_candidates: {
      id: string;
      label: string;
    }[];
    telegraphs: string[];
  };
}
export interface ErrorFrame {
  schema_version: "beat_frame/5";
  kind: "error";
  message: string;
}
export interface TraceFrame {
  schema_version: "beat_frame/5";
  kind: "trace";
  reasoning_log: BeatTrace;
}
export interface BeatTrace {
  decompose: TraceElement[];
  world_first?: TraceDecision[];
  attempts?: TraceAttempt[];
  rulings?: TraceRuling[];
  queries?: TraceQuery[];
  world_turn?: TraceWorldTurn[];
  halt_reason: string;
  committed: string[];
}
export interface TraceElement {
  type: string;
  stated?: string;
  ids?: string[];
}
export interface TraceDecision {
  actor_id: string;
  decision: "none" | "commit" | "telegraph";
  stated?: string;
}
export interface TraceAttempt {
  type: string;
  stated?: string;
  fact_sheet?: unknown;
  move_duration_s?: number;
  budget_remaining_before?: number;
  budget_remaining_after?: number;
  fit?: boolean;
}
export interface TraceRuling {
  actor_ids?: string[];
  fact_sheet?: unknown;
  reasoning: string;
  therefore: string;
  outcome?: string;
}
export interface TraceQuery {
  stated: string;
  fact_sheet?: unknown;
}
export interface TraceWorldTurn {
  clock_delta_s: number;
  fired_scheduled?: string[];
  rolls: TraceRoll[] | null;
  eruption?: TraceElement;
}
export interface TraceRoll {
  tier: string;
  chance: number;
  roll: number;
  fired: boolean;
}
