/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Supersedes narration/1, which folded a spoken line and the staging around it into one `text` string. That forced every consumer to guess where the quote began: the frontend could not style speech differently from prose, and the verbatim belt had to substring-match a whole sentence of narrator writing against a perception line. Splitting them makes the spoken words a first-class field — the UI formats them, and the belt checks exactly the words claimed to be spoken and nothing else.
 */
export type Narration2OrderedNarrationSegmentsSpeechCarriesItsVerbatimQuoteAsItsOwnFieldSeparateFromStagingProse = (
  | {
      speaker_id?: null;
      kind?: "narration";
      text?: {
        [k: string]: unknown;
      };
      quote?: null;
      [k: string]: unknown;
    }
  | {
      speaker_id?: string;
      kind?: "action";
      text?: {
        [k: string]: unknown;
      };
      quote?: null;
      [k: string]: unknown;
    }
  | {
      speaker_id?: string;
      kind?: "speech";
      quote?: string;
      [k: string]: unknown;
    }
)[];
