/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SceneCurrent2WhereYouAreWhoIsPresentWhatMattersNowGETWorldsWSceneCurrent {
  schema_version: "scene_current/3";
  place: {
    id: string;
    label: string;
    description: string | null;
    tone: string | null;
    /**
     * The play-surface BACKDROP for the place the viewer stands in. Not perception-scoped, for the same reason a portrait is not: the room you are standing in is not a secret, and what the viewer KNOWS about it is already carried by label and description. Image reference, or null when there is no picture yet — the ordinary state, and what the frontend's placeholder is for. It swaps in on a later read with no re-request and no subscription. Carries an asset id and a PATH back to the world backend, never a presigned URL: those expire (~15 min), so an embedded one would make this payload rot in any cache or log. Fetch as {apiBase}{path}, optionally ?tier=thumbnail|preview|final (256/768/1024, default preview); the backend mints a fresh short-lived URL per read and redirects.
     */
    image: null | {
      schema_version: "image_ref/1";
      asset_id: string;
      path: string;
    };
  };
  participants: {
    id: string;
    label: string;
    kind: "actor";
    /**
     * Image reference, or null when there is no picture yet — the ordinary state, and what the frontend's placeholder silhouette is for. It swaps in on a later read with no re-request and no subscription. Carries an asset id and a PATH back to the world backend, never a presigned URL: those expire (~15 min), so an embedded one would make this payload rot in any cache or log. Fetch as {apiBase}{path}, optionally ?tier=thumbnail|preview|final (256/768/1024, default preview); the backend mints a fresh short-lived URL per read and redirects.
     */
    image: null | {
      schema_version: "image_ref/1";
      asset_id: string;
      path: string;
    };
  }[];
  now: {
    tick: number;
    display_label: string | null;
  };
  journey: null | JourneyBlock;
  current: string[];
}
export interface JourneyBlock {
  active: boolean;
  kind: "travel" | "wait" | "watch";
  goal_label: string | null;
  where_label: string | null;
  progress: number;
  legs_done: number;
  legs_total: number;
  interruptible: boolean;
  status: "active" | "arrived" | "ended";
}
