/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * GET /worlds/{w}/transcript. Viewer-scoped. Unlike every other read surface this is a RECORD, not a projection: the prose a model wrote once cannot be recomputed from world state. Entries are returned exactly as they were delivered and are NEVER retro-labelled — an entry written before the viewer learned a name still says 'the muscle by the bar' after he learns 'Jonas', because a memory of an experience is itself a perception. History begins when the feature shipped; beats played before it are not stored and are not fabricated.
 */
export interface Transcript2TheViewerSLivedStoryDeliveredNarrationNewestFirstCursorPaginated {
  schema_version: "transcript/2";
  world_id: string;
  viewer_id: string;
  /**
   * Newest first. One entry per narrated beat.
   */
  entries: {
    /**
     * Monotonic per-row ordering handle and the pagination cursor. Not domain time: several entries can share one tick, so a tick cannot order or paginate them.
     */
    entry_no: number;
    /**
     * The in-world tick the beat started at (B-5 logical time). For display and grouping, never for ordering.
     */
    tick: number;
    /**
     * The player's own input, stored RAW — never parsed, never reformatted. Null when he typed nothing (a continue press), which is a different fact from an empty string.
     */
    stated: string | null;
    halt_reason: string | null;
    /**
     * The journey block as delivered, or null when the beat had none — the marker the frontend needs to render travel in history the way it rendered it live.
     */
    journey: {
      [k: string]: unknown;
    } | null;
    /**
     * The delivered narration, in order — the SAME message shape a live beat_frame/5 narration frame carries, so history and live prose render through one path.
     */
    segments: {
      speaker_id: string | null;
      /**
       * The label AS IT WAS at the time — deliberately frozen, never re-resolved against present knowledge.
       */
      speaker_label: string;
      kind: "narration" | "speech" | "action";
      /**
       * Prose. The whole segment for narration and action; for speech, the staging around the line, possibly empty.
       */
      text: string;
      /**
       * The verbatim spoken words. Non-empty exactly when kind is speech; null otherwise.
       */
      quote: string | null;
      /**
       * Optional per-line speaker emotion for sprite selection. Null/absent means neutral.
       */
      emotion?: "neutral" | "happy" | "angry" | "sad" | null;
    }[];
  }[];
  /**
   * Cursor for the next (older) page: pass as ?before=. Null means this page reached the beginning of the story — page until null rather than inferring the end from a short page.
   */
  next_before: number | null;
}
