/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorldGenesisFrame2ONESSEFrameOfPOSTWorldsGenesisAWorldBuildIsALongAuthoredActWithIntermediateResultsSoItStreamsForTheSameReasonABeatDoesEveryFrameNamesSomethingThatWasReallyAuthoredWorkingFramesCarryALineOfTheWorldSOwnLanguageAsEachPartLandsChoiceIsTheTerminalSuccessOfTheStreamTheStreamNowEndsInAChoiceNotAWorldTheWorldItselfArrivesLaterOnTheKickstartTurnSDoneTrueBecauseCommitNoLongerHappensInsideTheStreamRefusedMeansTheBriefCouldNotBecomeAWorldAndSaysWhyErrorMeansTheMachineFailedAndSaysSoWithoutPretendingToBeTheWorldSVoiceThereIsDeliberatelyNoProgressPercentageNoETAAndNoStageListAClientMustNeverRenderANumberNothingProducedFrontendLaw2 =
  {
    schema_version: "world_genesis_frame/2";
    kind: "working" | "choice" | "refused" | "error";
    /**
     * World-authored text on `working` and `refused`, an honest failure line on `error`. Renders VERBATIM — never rewritten, summarised or title-cased (frontend law 1).
     */
    stated?: string;
    /**
     * The draft's opaque handle. POST it to /worlds/genesis/kickstart with each answer. It expires; an expired handle is a stated refusal, and the build is simply made again.
     */
    handle?: string;
    question?: string;
    /**
     * @minItems 1
     */
    options?: [
      {
        label: string;
        implication?: string;
        /**
         * At most one option per question carries this.
         */
        recommended?: boolean;
      },
      ...{
        label: string;
        implication?: string;
        /**
         * At most one option per question carries this.
         */
        recommended?: boolean;
      }[]
    ];
  } & (
    | {
        kind?: "working" | "refused" | "error";
        [k: string]: unknown;
      }
    | {
        kind?: "choice";
        [k: string]: unknown;
      }
  );
