/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Refresh is append-only canon: it mints a NEW world id from the source world's template, archives the source world row, and returns the successor's directory entry. Nothing in the source world is deleted; the old id remains a historical reference.
 */
export interface WorldRefreshed1POSTWorldsIdRefresh200TheSuccessorDirectoryEntryAndTheSourceItSupersedes {
  schema_version: "world_refreshed/1";
  source_world_id: string;
  id: string;
  display_name: string;
  theme: {
    schema_version: "world_theme/1";
    accent: string;
    mood: string;
    ornament: string;
  };
  playable: true;
}
