/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WorldDirectory2GETWorldsTheWorldsACallerMayChooseBetweenSPEC028ADIRECTORYNeverCanonAnIdANameALineOfFictionALookACoverWhereYouLeftOffAndWhetherAnyoneCanPlayItNoWorldSTATEOnThisSurface {
  schema_version: "world_directory/2";
  worlds: {
    id: string;
    /**
     * The world's name as a chooser sees it. The one label in the system that is not viewer-relative, because it names the CONTAINER rather than anything inside it — B-1 governs what is in a world.
     */
    display_name: string;
    /**
     * ONE world-authored line selling the world on its card. AUTHORED FICTION (GA-2): this service never composes it — no default, no template. null when the world's author has not written one, and the card renders without it. Never an empty string; a blank is rejected at the column.
     */
    tagline: string | null;
    theme: WorldTheme1;
    /**
     * Whether this world states a player (world.player_entity_id). False for a world created through POST /worlds that has nothing authored into it yet — real, listed, and not yet enterable.
     */
    playable: boolean;
    /**
     * The world's cover art. Image reference, or null when there is no picture yet — the ordinary state, and what the frontend's placeholder is for. It swaps in on a later read with no re-request and no subscription. Carries an asset id and a PATH back to the world backend, never a presigned URL: those expire (~15 min), so an embedded one would make this payload rot in any cache or log. Fetch as {apiBase}{path}, optionally ?tier=thumbnail|preview|final (256/768/1024, default preview); the backend mints a fresh short-lived URL per read and redirects.
     */
    cover_image: null | {
      schema_version: "image_ref/1";
      asset_id: string;
      path: string;
    };
    /**
     * The world's own label for where its player stands, or left off. A LABEL AND NOTHING ELSE — no tick, no timestamp, no '2 hours ago' (B-5 keeps wall-clock off this boundary, and a directory is a shelf of doors, not a save-game list). Rendered as the world's player, whose whereabouts it is and who a caller becomes on entering. null when the world has no player yet, or has one who has never been placed anywhere — never entered, nothing to say.
     */
    last_place_label: string | null;
  }[];
}
/**
 * SPEC-019 theme tokens. ONE accent colour — the frontend derives the rest, because a backend shipping a palette would own visual design it has no business owning. mood is an ATMOSPHERE word, never a genre: the system never learns the word 'fantasy' (GA-3).
 */
export interface WorldTheme1 {
  schema_version: "world_theme/1";
  /**
   * A single hex colour.
   */
  accent: string;
  /**
   * Draft vocabulary: daylight | nocturne | mist | ember | bleak. Deliberately NOT constrained to that set — unknown values must DEGRADE in the client, never fail here. Enforcing the enum backend-side would make this service the thing that breaks on a word it has not heard of, which is backwards for a field whose purpose is to evolve.
   */
  mood: string;
  /**
   * Draft vocabulary: none | filigree | rivet | vine | circuit. Unconstrained for the same reason as mood.
   */
  ornament: string;
}
