/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorldGenesisFrame3ONESSEFrameOfPOSTWorldsGenesisAWorldBuildIsALongAuthoredActWithIntermediateResultsSoItStreamsForTheSameReasonABeatDoesEveryFrameNamesSomethingThatWasReallyAuthoredWorkingFramesCarryALineOfTheWorldSOwnLanguageAsEachPartLandsChoiceIsTheTerminalSuccessOfTheStreamItNowCarriesTheREALWorldIdBecauseTheWorldCommitsWhenAuthoringEndsDurableWorlds20260821TheWorldAlreadyExistsListedAsNotYetEnterableAndOnlyThePlayerAndTheArrivalWaitForTheKickstartAnswersRefusedMeansTheBriefCouldNotBecomeAWorldAndSaysWhyErrorMeansTheMachineFailedAndSaysSoWithoutPretendingToBeTheWorldSVoiceEitherMayCarryWorldIdWhenTheWorldHadAlreadyCommittedBeforeTheFailureThatWorldIsResumableNotLostThereIsDeliberatelyNoProgressPercentageNoETAAndNoStageListLaw2NeverInventADisplayedValue =
  {
    schema_version: "world_genesis_frame/3";
    kind: "working" | "choice" | "refused" | "error";
    /**
     * World-authored text on `working` and `refused`, an honest failure line on `error`. Renders VERBATIM — never rewritten, summarised or title-cased (frontend law 1).
     */
    stated?: string;
    question?: string;
    /**
     * @minItems 1
     */
    options?: [
      {
        label: string;
        implication?: string;
        /**
         * At most one option per question carries this.
         */
        recommended?: boolean;
      },
      ...{
        label: string;
        implication?: string;
        /**
         * At most one option per question carries this.
         */
        recommended?: boolean;
      }[]
    ];
    /**
     * The committed world's id. Always present on `choice` — POST it to /worlds/genesis/kickstart with each answer (an empty answer re-serves the pending question: the resume path). Present on `refused`/`error` only when the world had committed before the failure.
     */
    world_id?: string;
  } & (
    | {
        kind?: "working" | "refused" | "error";
        [k: string]: unknown;
      }
    | {
        kind?: "choice";
        [k: string]: unknown;
      }
  );
