/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorldKickstartTurn2TheResponseToPOSTWorldsGenesisKickstartSameGrammarAsTheInterviewTurnDoneFalseCarriesTheNextQuestionDoneTrueCarriesTheWorldBuiltAndPlayableTheRequestIsWorldIdAnswerAnEmptyAnswerReServesThePendingQuestionWhichIsHowAnUnfinishedCreationResumesAfterAnyInterruptionTheFreeTextAnswerIsAPropertyOfTheSurfaceAndIsDeliberatelyNotEnumeratedHere =
  {
    schema_version: "world_kickstart_turn/2";
    done: boolean;
    question?: string;
    why?: string;
    /**
     * @minItems 1
     */
    options?: [
      {
        label: string;
        implication?: string;
        /**
         * At most one option per turn carries this.
         */
        recommended?: boolean;
      },
      ...{
        label: string;
        implication?: string;
        /**
         * At most one option per turn carries this.
         */
        recommended?: boolean;
      }[]
    ];
    world?: {
      id: string;
      display_name: string;
      tagline: string;
      playable: true;
    };
  } & (
    | {
        done?: false;
        [k: string]: unknown;
      }
    | {
        done?: true;
        [k: string]: unknown;
      }
  );
