/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorldInterviewTurn1TheResponseToPOSTWorldsInterviewONEQuestionAboutABriefOrNothingLeftToAskTheExchangeIsSTATELESSTheClientSendsTheBriefAndEveryPriorAnswerAndReceivesOneTurnSoThereIsNoSessionNoStoredInterviewAndNothingToResumeDoneTrueArrivesWithNoQuestionAndIsAGoodAnswerNotAFailureABriefThatLeavesNothingUndeterminedShouldBeAskedNothingAndTheSurfaceAlwaysLetsTheUserBuildImmediatelyRegardless =
  {
    schema_version: "world_interview_turn/1";
    /**
     * true when nothing is worth asking. The client stops the interview and offers the build.
     */
    done: boolean;
    /**
     * Present only when done is false. Renders verbatim.
     */
    question?: string;
    /**
     * Optional single line on what this question changes about the world, shown beneath it.
     */
    why?: string;
    /**
     * Present only when done is false. Offered answers, always accompanied on the surface by a free-text field the user may type into instead — that field is a property of the surface and is deliberately not enumerated here.
     *
     * @minItems 1
     */
    options?: [
      {
        label: string;
        /**
         * What choosing this would make true about the world.
         */
        implication?: string;
        /**
         * At most one option per turn carries this. The surface highlights it as the default.
         */
        recommended?: boolean;
      },
      ...{
        label: string;
        /**
         * What choosing this would make true about the world.
         */
        implication?: string;
        /**
         * At most one option per turn carries this. The surface highlights it as the default.
         */
        recommended?: boolean;
      }[]
    ];
  } & (
    | {
        done: true;
        [k: string]: unknown;
      }
    | {
        done?: false;
        [k: string]: unknown;
      }
  );
