/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorldIdIndexRouteImport } from './routes/w.$worldId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorldIdIndexRoute = WWorldIdIndexRouteImport.update({
  id: '/w/$worldId/',
  path: '/w/$worldId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$worldId/': typeof WWorldIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w/$worldId': typeof WWorldIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$worldId/': typeof WWorldIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/w/$worldId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/w/$worldId'
  id: '__root__' | '/' | '/w/$worldId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WWorldIdIndexRoute: typeof WWorldIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$worldId/': {
      id: '/w/$worldId/'
      path: '/w/$worldId'
      fullPath: '/w/$worldId/'
      preLoaderRoute: typeof WWorldIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WWorldIdIndexRoute: WWorldIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
