/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as WWorldIdIndexRouteImport } from './routes/w.$worldId.index'
import { Route as WWorldIdPlayRouteImport } from './routes/w.$worldId.play'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorldIdIndexRoute = WWorldIdIndexRouteImport.update({
  id: '/w/$worldId/',
  path: '/w/$worldId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorldIdPlayRoute = WWorldIdPlayRouteImport.update({
  id: '/w/$worldId/play',
  path: '/w/$worldId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/worlds': typeof WorldsRoute
  '/w/$worldId/play': typeof WWorldIdPlayRoute
  '/w/$worldId/': typeof WWorldIdIndexRoute
}
export interface FileRoutesByTo {
  '/worlds': typeof WorldsRoute
  '/w/$worldId/play': typeof WWorldIdPlayRoute
  '/w/$worldId': typeof WWorldIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/worlds': typeof WorldsRoute
  '/w/$worldId/play': typeof WWorldIdPlayRoute
  '/w/$worldId/': typeof WWorldIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/worlds' | '/w/$worldId/play' | '/w/$worldId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/worlds' | '/w/$worldId/play' | '/w/$worldId'
  id: '__root__' | '/worlds' | '/w/$worldId/play' | '/w/$worldId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorldsRoute: typeof WorldsRoute
  WWorldIdPlayRoute: typeof WWorldIdPlayRoute
  WWorldIdIndexRoute: typeof WWorldIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$worldId/': {
      id: '/w/$worldId/'
      path: '/w/$worldId'
      fullPath: '/w/$worldId/'
      preLoaderRoute: typeof WWorldIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$worldId/play': {
      id: '/w/$worldId/play'
      path: '/w/$worldId/play'
      fullPath: '/w/$worldId/play'
      preLoaderRoute: typeof WWorldIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  WorldsRoute: WorldsRoute,
  WWorldIdPlayRoute: WWorldIdPlayRoute,
  WWorldIdIndexRoute: WWorldIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
